# Generated by Django 4.2.7 on 2023-11-04 21:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cover', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.CharField(choices=[('new', 'New'), ('quoted', 'Quoted'), ('active', 'Active')], default='new', max_length=10)),
                ('is_accepted', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_band', models.CharField(max_length=50)),
                ('quoted_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.policy')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyStateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('new', 'New'), ('quoted', 'Quoted'), ('active', 'Active')], max_length=10)),
                ('date_changed', models.DateTimeField(default=datetime.timezone)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_history', to='quotes.policy')),
            ],
        ),
    ]
